version: '3'
services:
  web:
    build: src/Classifier.Web
    ports:
    - "8082:80"
  worker:
    build: src/Classifier.Worker
    environment:
      API_BASE_URL: "http://web"
    volumes:
    - ./ignore/images:/app/assets/images